package com.exedio.cope.builder.test.packagePrivate;

import com.exedio.cope.EnumField;
import com.exedio.cope.Item;
import com.exedio.cope.ItemField;
import com.exedio.cope.pattern.CompositeField;
import com.exedio.cope.pattern.Money;
import com.exedio.cope.pattern.MoneyField;
import com.exedio.cope.pattern.RangeField;

/**
 * @cope.constructor none
 * @cope.generic.constructor none
 */
final class MyItem extends Item implements Money.Currency
{
	static final EnumField<MyEnum> enumF = EnumField.create(MyEnum.class).optional();
	static final ItemField<MyItem> item = ItemField.create(MyItem.class).optional();
	static final CompositeField<MyComposite> composite = CompositeField.create(MyComposite.class).optional();

	static final RangeField<MyEnum> rangeEnum = RangeField.create(EnumField.create(MyEnum.class).optional());
	//static final RangeField<MyItem> rangeItem = RangeField.create(ItemField.create(MyItem.class).optional()); TODO not yet supported by cope

	static final MoneyField<MyEnum> moneyEnum = MoneyField.exclusive(EnumField.create(MyEnum.class)).optional();
	static final MoneyField<MyItem> moneyItem = MoneyField.exclusive(ItemField.create(MyItem.class)).optional();


	/**

	 **
	 * Returns the value of {@link #enumF}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final MyEnum getEnumF()
	{
		return MyItem.enumF.get(this);
	}/**

	 **
	 * Sets a new value for {@link #enumF}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setEnumF(final MyEnum enumF)
	{
		MyItem.enumF.set(this,enumF);
	}/**

	 **
	 * Returns the value of {@link #item}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final MyItem getItem()
	{
		return MyItem.item.get(this);
	}/**

	 **
	 * Sets a new value for {@link #item}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setItem(final MyItem item)
	{
		MyItem.item.set(this,item);
	}/**

	 **
	 * Returns the value of {@link #composite}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final MyComposite getComposite()
	{
		return MyItem.composite.get(this);
	}/**

	 **
	 * Sets a new value for {@link #composite}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setComposite(final MyComposite composite)
	{
		MyItem.composite.set(this,composite);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.Range<MyEnum> getRangeEnum()
	{
		return MyItem.rangeEnum.get(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setRangeEnum(final com.exedio.cope.pattern.Range<? extends MyEnum> rangeEnum)
	{
		MyItem.rangeEnum.set(this,rangeEnum);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getFrom public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final MyEnum getRangeEnumFrom()
	{
		return MyItem.rangeEnum.getFrom(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getTo public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final MyEnum getRangeEnumTo()
	{
		return MyItem.rangeEnum.getTo(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setFrom public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setRangeEnumFrom(final MyEnum rangeEnum)
	{
		MyItem.rangeEnum.setFrom(this,rangeEnum);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setTo public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setRangeEnumTo(final MyEnum rangeEnum)
	{
		MyItem.rangeEnum.setTo(this,rangeEnum);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.doesContain public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean doesRangeEnumContain(final MyEnum rangeEnum)
	{
		return MyItem.rangeEnum.doesContain(this,rangeEnum);
	}/**

	 **
	 * Returns the value of {@link #moneyEnum}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.Money<MyEnum> getMoneyEnum()
	{
		return MyItem.moneyEnum.get(this);
	}/**

	 **
	 * Sets a new value for {@link #moneyEnum}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setMoneyEnum(final com.exedio.cope.pattern.Money<MyEnum> moneyEnum)
	{
		MyItem.moneyEnum.set(this,moneyEnum);
	}/**

	 **
	 * Returns the value of {@link #moneyItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.Money<MyItem> getMoneyItem()
	{
		return MyItem.moneyItem.get(this);
	}/**

	 **
	 * Sets a new value for {@link #moneyItem}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setMoneyItem(final com.exedio.cope.pattern.Money<MyItem> moneyItem)
	{
		MyItem.moneyItem.set(this,moneyItem);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for myItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final com.exedio.cope.Type<MyItem> TYPE = com.exedio.cope.TypesBound.newType(MyItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private MyItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
