package com.exedio.cope.builder.test;

import com.exedio.cope.IntegerField;

/**
 * @cope.constructor none
 * @cope.generic.constructor none
 */
public class ConcreteLevel3Item extends MixedLevel2Item
{
	/**
	 * @cope.get public
	 */
	static final IntegerField l3 = new IntegerField().toFinal();

/**

	 **
	 * Returns the value of {@link #l3}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final int getL3()
	{
		return ConcreteLevel3Item.l3.getMandatory(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for concreteLevel3Item.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<ConcreteLevel3Item> TYPE = com.exedio.cope.TypesBound.newType(ConcreteLevel3Item.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	protected ConcreteLevel3Item(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
