package com.exedio.cope.builder.test;

import com.exedio.cope.IntegerField;

/**
 * @cope.constructor none
 * @cope.generic.constructor none
 */
public class MixedLevel2Item extends AbstractLevel1Item
{
	/**
	 * @cope.get public
	 */
	static final IntegerField l2 = new IntegerField().toFinal();

/**

	 **
	 * Returns the value of {@link #l2}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	public final int getL2()
	{
		return MixedLevel2Item.l2.getMandatory(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for mixedLevel2Item.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<MixedLevel2Item> TYPE = com.exedio.cope.TypesBound.newType(MixedLevel2Item.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	protected MixedLevel2Item(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
