package com.exedio.cope.builder.test;

import com.exedio.cope.Item;
import com.exedio.cope.pattern.Schedule;
import com.exedio.cope.pattern.Scheduleable;
import com.exedio.cope.util.JobContext;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

/**
 * @cope.constructor none
 * @cope.generic.constructor none
 */
final class SourcePatternItem extends Item implements Scheduleable
{
	static final Schedule schedule = new Schedule(TimeZone.getDefault(), Locale.GERMANY);

	@Override
	public void run(final Schedule schedule, final Date from, final Date until, final JobContext ctx)
	{
		throw new RuntimeException();
	}

	/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.isEnabled public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final boolean isScheduleEnabled()
	{
		return SourcePatternItem.schedule.isEnabled(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setEnabled public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setScheduleEnabled(final boolean enabled)
	{
		SourcePatternItem.schedule.setEnabled(this,enabled);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getInterval public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final com.exedio.cope.pattern.Schedule.Interval getScheduleInterval()
	{
		return SourcePatternItem.schedule.getInterval(this);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setInterval public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final void setScheduleInterval(final com.exedio.cope.pattern.Schedule.Interval interval)
	{
		SourcePatternItem.schedule.setInterval(this,interval);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.run public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	@Deprecated
	static final int runSchedule(final com.exedio.cope.util.Interrupter interrupter)
	{
		return SourcePatternItem.schedule.run(SourcePatternItem.class,interrupter);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.run public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final void runSchedule(final com.exedio.cope.util.JobContext ctx)
	{
		SourcePatternItem.schedule.run(SourcePatternItem.class,ctx);
	}/**

	 **
	 * Returns the parent field of the run type of {@link #schedule}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.RunParent public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final com.exedio.cope.ItemField<SourcePatternItem> scheduleRunParent()
	{
		return SourcePatternItem.schedule.getRunParent(SourcePatternItem.class);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for sourcePatternItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final com.exedio.cope.Type<SourcePatternItem> TYPE = com.exedio.cope.TypesBound.newType(SourcePatternItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private SourcePatternItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
