package com.exedio.cope.builder.test;

import com.exedio.cope.IntegerField;
import com.exedio.cope.Item;
import com.exedio.cope.ItemField;
import com.exedio.cope.pattern.PartOf;

/**
 * @cope.constructor none
 * @cope.generic.constructor none
 */
final class UnknownPatternItem extends Item
{
	static final ItemField<SimpleItem> parent = ItemField.create(SimpleItem.class).toFinal();
	static final IntegerField order = new IntegerField().toFinal();
	static final PartOf<SimpleItem> unknowns = PartOf.create(parent, order);

	/**

	 **
	 * Returns the value of {@link #parent}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final SimpleItem getParent()
	{
		return UnknownPatternItem.parent.get(this);
	}/**

	 **
	 * Returns the value of {@link #order}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.get public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final int getOrder()
	{
		return UnknownPatternItem.order.getMandatory(this);
	}/**

	 **
	 * Returns the container this item is part of by {@link #unknowns}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getContainer public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	final SimpleItem getUnknownsContainer()
	{
		return UnknownPatternItem.unknowns.getContainer(this);
	}/**

	 **
	 * Returns the parts of the given container.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getParts public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final java.util.List<UnknownPatternItem> getUnknownsParts(final SimpleItem container)
	{
		return UnknownPatternItem.unknowns.getParts(UnknownPatternItem.class,container);
	}/**

	 **
	 * Returns the parts of the given container matching the given condition.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getParts public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final java.util.List<UnknownPatternItem> getUnknownsParts(final SimpleItem container,final com.exedio.cope.Condition condition)
	{
		return UnknownPatternItem.unknowns.getParts(UnknownPatternItem.class,container,condition);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for unknownPatternItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	static final com.exedio.cope.Type<UnknownPatternItem> TYPE = com.exedio.cope.TypesBound.newType(UnknownPatternItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	@javax.annotation.Generated("com.exedio.cope.instrument")
	private UnknownPatternItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
